ServerEvents.tags('item', event => {
    // [material, chipped_exclusion]
    const chippedMaterials = [
        ['amethyst_block',         null],
        ['basalt',                 null],
        ['blackstone',             '(?!.*gilded_blackstone)'],
        ['blue_ice',               null],
        ['bone_block',             null],
        ['brown_mushroom_block',   null],
        ['brown_mushroom',         '(?!.*brown_mushroom_block)'],
        ['cobbled_deepslate',      null],
        ['cobweb',                 null],
        ['copper_block',           null],
        ['crimson_fungus',         null],
        ['crimson_roots',          null],
        ['crimson_stem',           '(?!.*stripped)'],
        ['crying_obsidian',        null],
        ['dark_prismarine',        null],
        ['diamond_block',          null],
        ['dripstone_block',        null],
        ['pointed_dripstone',      null],
        ['gilded_blackstone',      null],
        ['gravel',                 null],
        ['hay_block',              null],
        ['iron_bars',              null],
        ['ladder',                 null],
        ['lantern',                '(?!.*sea_lantern)'],
        ['lily_pad',               null],
        ['lodestone',              null],
        ['magma_block',            null],
        ['mangrove_roots',         null],
        ['melon',                  null],
        ['moss_block',             null],
        ['mossy_cobblestone',      null],
        ['mud',                    '(?!.*packed_mud)'],
        ['mushroom_stem',          null],
        ['netherite_block',        null],
        ['netherrack',             null],
        ['nether_sprouts',         null],
        ['nether_wart_block',      null],
        ['obsidian',               '(?!.*crying_obsidian)'],
        ['ochre_froglight',        null],
        ['packed_mud',             null],
        ['pearlescent_froglight',  null],
        ['raw_copper_block',       null],
        ['red_mushroom_block',     null],
        ['red_mushroom',           '(?!.*red_mushroom_block)'],
        ['red_nether_bricks',      null],
        ['redstone_lamp',          null],
        ['sand',                   null],
        ['sea_lantern',            null],
        ['shroomlight',            null],
        ['snow_block',             null],
        ['soul_sand',              null],
        ['sponge',                 null],
        ['stripped_crimson_stem',  null],
        ['stripped_warped_stem',   null],
        ['tuff',                   null],
        ['verdant_froglight',      null],
        ['vine',                   null],
        ['warped_fungus',          null],
        ['warped_roots',           null],
        ['warped_stem',            '(?!.*stripped)'],
        ['warped_wart_block',      null],
        ['waxed_copper_block',     null],
        ['waxed_exposed_copper',   null],
        ['waxed_oxidized_copper',  null],
        ['waxed_weathered_copper', null],
        ['ancient_debris',         null],
        ['barrel',                 null],
        ['bookshelf',              null],
        ['calcite',                null],
        ['clay',                   null],
        ['crate',                  null],
        ['dried_kelp_block',       null],
        ['torch',                  null],
    ]

    chippedMaterials.forEach(([material, excl]) => {
        event.add(`chipped:${material}`, [
            new RegExp(`^rechiseled:${material}(?!.*(?:stairs?|slab))[a-z_]*$`),
            new RegExp(`^chipped:${excl ?? ''}(?!.*(?:stairs?|slab))(?:[a-z]+_)*${material}(?:_[a-z]+)*$`),
        ])
    })

    // Pumpkin variants (some use 'kin' suffix without 'pumpkin' in name)
    event.add('chipped:pumpkin', [/^chipped:(?:[a-z_]*pumpkin[a-z_]*|[a-z_]+kin)$/])
})
