/**
 * EMI++ groups
 *
 * Tag group - creates an EMI group from a tag, optionally merging sources into it:
 * { type: "tag", name: string, tag: string, sources?: string[] }
 *
 * Item group - a plain list of items without creating a tag:
 * { type: "group", name: string, items: string[] }
 * 
 * Override with "mod" (default is "milf")
 * 
 */
global.emixxGroups = [
    {
        type: "tag",
        name: "glyphs",
        tag: "milf:glyphs",
        sources: ["#ars_nouveau:tier_2_glyphs", "#ars_nouveau:tier_1_glyphs", "#ars_nouveau:tier_3_glyphs"],
    },
    {
        type: "group",
        name: "bamboo_spikes_tipped",
        items: [
            "supplementaries:bamboo_spikes_tipped"
        ],
    },
    {
        type: "group",
        mod: "minecraft",
        name: "paintings",
        items: [
            "minecraft:painting",
            "eternal_starlight:starlit_painting",
        ],
    },
    {
        type: "group",
        mod: "minecraft",
        name: "goat_horns",
        items: [
            "minecraft:goat_horn",
            "horseman:copper_horn",
        ],
    },
    {
        type: "group",
        name: "gems",
        items: [
            "apotheosis:gem"
        ],
    },
    {
        type: "group",
        name: "blueprints",
        items: [
            "immersiveengineering:blueprint"
        ],
    },
    {
        type: "group",
        name: "potion_buckets",
        items: [
            "immersiveengineering:potion_bucket"
        ],
    },
    {
        type: "group",
        name: "gate_pearls",
        items: [
            "gateways:gate_pearl"
        ],
    },
    {
        type: "group",
        name: "backpacks",
        items: [
            "sophisticatedbackpacks:backpack",
            'sophisticatedbackpacks:copper_backpack',
            'sophisticatedbackpacks:iron_backpack',
            'sophisticatedbackpacks:gold_backpack',
            'sophisticatedbackpacks:diamond_backpack',
            'sophisticatedbackpacks:netherite_backpack'
        ],
    },
    {
        type: "group",
        name: "data_models",
        items: [
            "hostilenetworks:data_model"
        ],
    },
    {
        type: "group",
        name: "predictions",
        items: [
            "hostilenetworks:prediction"
        ],
    },
    {
        type: "group",
        name: "memorys",
        items: [
            "spectrum:memory"
        ],
    },
    {
        type: "group",
        name: "ink_flasks",
        items: [
            "spectrum:ink_flask"
        ],
    },
    {
        type: "group",
        name: "upgrade_tome",
        items: [
            "neovitae:upgrade_tome"
        ],
    },
    { type: "tag", name: "item_shelves", tag: "suppsquared:item_shelves" },
    { type: "tag", name: "nubs", tag: "architects_palette:nubs" },
    { type: "tag", name: "candle_holders", tag: "supplementaries:candle_holders" },
    { type: "tag", name: "flags", tag: "supplementaries:flags" },
    { type: "tag", name: "awnings", tag: "supplementaries:awnings" },
    { type: "tag", name: "sleeping_bags", tag: "comforts:sleeping_bags" },
    { type: "tag", name: "hammocks", tag: "comforts:hammocks" },
    { type: "tag", name: "sacks", tag: "supplementaries:sacks" },
    { type: "tag", name: "trapped_presents", tag: "supplementaries:trapped_presents" },
    { type: "tag", name: "presents", tag: "supplementaries:presents" },
    { type: "tag", name: "paintbrushes", tag: "arts_and_crafts:paintbrushes" },
    { type: "tag", name: "rods", tag: "c:rods" },
    { type: "tag", name: "plates", tag: "c:plates" },
    { type: "tag", name: "gears", tag: "c:gears" },
    { type: "tag", name: "rings", tag: "c:rings" },
    { type: "tag", name: "bolts", tag: "c:bolts" },
    { type: "tag", name: "curved_plates", tag: "c:curved_plates" },
    { type: "tag", name: "large_plates", tag: "c:large_plates" },
    { type: "tag", name: "double_ingots", tag: "c:double_ingots" },
    { type: "tag", name: "tiny_dusts", tag: "c:tiny_dusts" },
    { type: "tag", name: "paint_balls", tag: "ae2:paint_balls" },
    { type: "tag", name: "way_signs", tag: "supplementaries:way_signs" },
    { type: "tag", name: "decorated_pots", tag: "arts_and_crafts:decorated_pots" },
    { type: "tag", name: "shaders", tag: "immersiveengineering:shaders" },
    { type: "tag", name: "sheetmetals", tag: "c:sheetmetals" },
    { type: "tag", name: "chutes", tag: "immersiveengineering:chutes" },
    { type: "tag", name: "drying_racks", tag: "ytech:drying_racks" },
    { type: "tag", name: "ritual_dummies", tag: "occultism:ritual_dummies" },
    { type: "tag", name: "upgrades", tag: "sophisticatedbackpacks:upgrade" },
    { type: "tag", name: "jelly_blocks", tag: "fruitsdelight:jelly_blocks" },
    { type: "tag", name: "fish_templates", tag: "starcatcher:templates" },
    { type: "tag", name: "fishing_rods", tag: "c:tools/fishing_rod" },
    { type: "tag", name: "end_eyes", tag: "endrem:eyes" },
    { type: "tag", name: "swords", tag: "c:swords" },
    { type: "tag", name: "swords", tag: "c:swords" },
    { type: "tag", name: "aviaries", tag: "animal_pen:aviaries" },
    { type: "tag", name: "animal_pens", tag: "animal_pen:animal_pens" },
    //{ type: "tag", name: "multiblock_items", tag: "milf:multiblock_items" },
    { type: "tag", name: "placers", tag: "milf:placers" },
    { type: "tag", name: "empty_box", tag: "milf:empty_box" },
    { type: "tag", name: "idols", tag: "spectrum:idols" },
    { type: "tag", name: "skulls", tag: "c:skulls" },
    { type: "tag", name: "buntings", tag: "supplementaries:buntings" },
    { type: "tag", name: "chalks", tag: "arts_and_crafts:chalks" },
    { type: "tag", name: "plasters", tag: "arts_and_crafts:plasters" },
    { type: "tag", name: "flower_pots", tag: "arts_and_crafts:flower_pots" },
    { type: "tag", name: "mud_bricks", tag: "arts_and_crafts:mud_bricks" },
    { type: "tag", name: "factory", tag: "factory_blocks:factory" },
    { type: "tag", name: "tools_chalk", tag: "occultism:tools/chalk" },
    { type: "tag", name: "chisel_andesite", tag: "milf:chisel_andesite" },
    { type: "tag", name: "chisel_black_concrete", tag: "milf:chisel_black_concrete" },
    { type: "tag", name: "chisel_blue_concrete", tag: "milf:chisel_blue_concrete" },
    { type: "tag", name: "chisel_bricks", tag: "milf:chisel_bricks" },
    { type: "tag", name: "chisel_brown_concrete", tag: "milf:chisel_brown_concrete" },
    { type: "tag", name: "chisel_coal_block", tag: "milf:chisel_coal_block" },
    { type: "tag", name: "chisel_cobblestone", tag: "milf:chisel_cobblestone" },
    { type: "tag", name: "chisel_cyan_concrete", tag: "milf:chisel_cyan_concrete" },
    { type: "tag", name: "chisel_deepslate", tag: "milf:chisel_deepslate" },
    { type: "tag", name: "chisel_diorite", tag: "milf:chisel_diorite" },
    { type: "tag", name: "chisel_dirt", tag: "milf:chisel_dirt" },
    { type: "tag", name: "chisel_emerald_block", tag: "milf:chisel_emerald_block" },
    { type: "tag", name: "chisel_end_stone", tag: "milf:chisel_end_stone" },
    { type: "tag", name: "chisel_glass", tag: "milf:chisel_glass" },
    { type: "tag", name: "chisel_glowstone", tag: "milf:chisel_glowstone" },
    { type: "tag", name: "chisel_gold_block", tag: "milf:chisel_gold_block" },
    { type: "tag", name: "chisel_granite", tag: "milf:chisel_granite" },
    { type: "tag", name: "chisel_gray_concrete", tag: "milf:chisel_gray_concrete" },
    { type: "tag", name: "chisel_green_concrete", tag: "milf:chisel_green_concrete" },
    { type: "tag", name: "chisel_ice", tag: "milf:chisel_ice" },
    { type: "tag", name: "chisel_iron_block", tag: "milf:chisel_iron_block" },
    { type: "tag", name: "chisel_lapis_block", tag: "milf:chisel_lapis_block" },
    { type: "tag", name: "chisel_light_blue_concrete", tag: "milf:chisel_light_blue_concrete" },
    { type: "tag", name: "chisel_light_gray_concrete", tag: "milf:chisel_light_gray_concrete" },
    { type: "tag", name: "chisel_lime_concrete", tag: "milf:chisel_lime_concrete" },
    { type: "tag", name: "chisel_magenta_concrete", tag: "milf:chisel_magenta_concrete" },
    { type: "tag", name: "chisel_nether_brick", tag: "milf:chisel_nether_brick" },
    { type: "tag", name: "chisel_orange_concrete", tag: "milf:chisel_orange_concrete" },
    { type: "tag", name: "chisel_pink_concrete", tag: "milf:chisel_pink_concrete" },
    { type: "tag", name: "chisel_prismarine", tag: "milf:chisel_prismarine" },
    { type: "tag", name: "chisel_purple_concrete", tag: "milf:chisel_purple_concrete" },
    { type: "tag", name: "chisel_purpur", tag: "milf:chisel_purpur" },
    { type: "tag", name: "chisel_quartz", tag: "milf:chisel_quartz" },
    { type: "tag", name: "chisel_red_concrete", tag: "milf:chisel_red_concrete" },
    { type: "tag", name: "chisel_red_sandstone", tag: "milf:chisel_red_sandstone" },
    { type: "tag", name: "chisel_redstone_block", tag: "milf:chisel_redstone_block" },
    { type: "tag", name: "chisel_sandstone", tag: "milf:chisel_sandstone" },
    { type: "tag", name: "chisel_stone", tag: "milf:chisel_stone" },
    { type: "tag", name: "chisel_white_concrete", tag: "milf:chisel_white_concrete" },
    { type: "tag", name: "chisel_yellow_concrete", tag: "milf:chisel_yellow_concrete" },
    { type: "tag", name: "chipped_amethyst_block", tag: "chipped:amethyst_block" },
    { type: "tag", name: "chipped_crying_obsidian", tag: "chipped:crying_obsidian" },
    { type: "tag", name: "chipped_netherite_block", tag: "chipped:netherite_block" },
    { type: "tag", name: "chipped_diamond_block", tag: "chipped:diamond_block" },
    { type: "tag", name: "chipped_sponge", tag: "chipped:sponge" },
    { type: "tag", name: "chipped_waxed_copper_block", tag: "chipped:waxed_copper_block" },
    { type: "tag", name: "chipped_waxed_exposed_copper", tag: "chipped:waxed_exposed_copper" },
    { type: "tag", name: "chipped_waxed_weathered_copper", tag: "chipped:waxed_weathered_copper" },
    { type: "tag", name: "chipped_waxed_oxidized_copper", tag: "chipped:waxed_oxidized_copper" },
    { type: "tag", name: "chipped_snow_block", tag: "chipped:snow_block" },
    { type: "tag", name: "chipped_clay", tag: "chipped:clay" },
    { type: "tag", name: "chipped_mud", tag: "chipped:mud" },
    { type: "tag", name: "chipped_packed_mud", tag: "chipped:packed_mud" },
    { type: "tag", name: "chipped_mangrove_roots", tag: "chipped:mangrove_roots" },
    { type: "tag", name: "chipped_ochre_froglight", tag: "chipped:ochre_froglight" },
    { type: "tag", name: "chipped_pearlescent_froglight", tag: "chipped:pearlescent_froglight" },
    { type: "tag", name: "chipped_brown_mushroom_block", tag: "chipped:brown_mushroom_block" },
    { type: "tag", name: "chipped_red_mushroom_block", tag: "chipped:red_mushroom_block" },
    { type: "tag", name: "chipped_mushroom_stem", tag: "chipped:mushroom_stem" },
    { type: "tag", name: "chipped_melon", tag: "chipped:melon" },
    { type: "tag", name: "chipped_hay_block", tag: "chipped:hay_block" },
    { type: "tag", name: "chipped_shroomlight", tag: "chipped:shroomlight" },
    { type: "tag", name: "chipped_soul_sand", tag: "chipped:soul_sand" },
    { type: "tag", name: "chipped_dried_kelp_block", tag: "chipped:dried_kelp_block" },
    { type: "tag", name: "chipped_warped_roots", tag: "chipped:warped_roots" },
    { type: "tag", name: "chipped_lily_pad", tag: "chipped:lily_pad" },
    { type: "tag", name: "chipped_nether_sprouts", tag: "chipped:nether_sprouts" },
    { type: "tag", name: "chipped_nether_wart_block", tag: "chipped:nether_wart_block" },
    { type: "tag", name: "chipped_pumpkin", tag: "chipped:pumpkin" },
    { type: "tag", name: "chipped_vine", tag: "chipped:vine" },
    { type: "tag", name: "chipped_crimson_fungus", tag: "chipped:crimson_fungus" },
    { type: "tag", name: "chipped_crimson_stem", tag: "chipped:crimson_stem" },
    { type: "tag", name: "chipped_stripped_crimson_stem", tag: "chipped:stripped_crimson_stem" },
    { type: "tag", name: "chipped_stripped_warped_stem", tag: "chipped:stripped_warped_stem" },
    { type: "tag", name: "chipped_barrel", tag: "chipped:barrel" },
    { type: "tag", name: "chipped_crate", tag: "chipped:crate" },
    { type: "tag", name: "chipped_bookshelf", tag: "chipped:bookshelf" },
    { type: "tag", name: "chipped_ladder", tag: "chipped:ladder" },
    { type: "tag", name: "chipped_ancient_debris", tag: "chipped:ancient_debris" },
    { type: "tag", name: "chipped_torch", tag: "chipped:torch" },
    { type: "tag", name: "chipped_basalt", tag: "chipped:basalt" },
    { type: "tag", name: "chipped_calcite", tag: "chipped:calcite" },
    { type: "tag", name: "chipped_magma_block", tag: "chipped:magma_block" },
    { type: "tag", name: "chipped_obsidian", tag: "chipped:obsidian" },
    { type: "tag", name: "chipped_netherrack", tag: "chipped:netherrack" },
    { type: "tag", name: "chipped_tuff", tag: "chipped:tuff" },
    { type: "tag", name: "chipped_iron_bars", tag: "chipped:iron_bars" },
    { type: "tag", name: "chipped_sea_lantern", tag: "chipped:sea_lantern" },
    { type: "tag", name: "chipped_lantern", tag: "chipped:lantern" },
    { type: "tag", name: "chipped_blackstone", tag: "chipped:blackstone" },
    { type: "tag", name: "chipped_blue_ice", tag: "chipped:blue_ice" },
    { type: "tag", name: "chipped_bone_block", tag: "chipped:bone_block" },
    { type: "tag", name: "chipped_brown_mushroom", tag: "chipped:brown_mushroom" },
    { type: "tag", name: "chipped_cobbled_deepslate", tag: "chipped:cobbled_deepslate" },
    { type: "tag", name: "chipped_cobweb", tag: "chipped:cobweb" },
    { type: "tag", name: "chipped_copper_block", tag: "chipped:copper_block" },
    { type: "tag", name: "chipped_crimson_roots", tag: "chipped:crimson_roots" },
    { type: "tag", name: "chipped_dark_prismarine", tag: "chipped:dark_prismarine" },
    { type: "tag", name: "chipped_dripstone_block", tag: "chipped:dripstone_block" },
    { type: "tag", name: "chipped_pointed_dripstone", tag: "chipped:pointed_dripstone" },
    { type: "tag", name: "chipped_gilded_blackstone", tag: "chipped:gilded_blackstone" },
    { type: "tag", name: "chipped_gravel", tag: "chipped:gravel" },
    { type: "tag", name: "chipped_lodestone", tag: "chipped:lodestone" },
    { type: "tag", name: "chipped_moss_block", tag: "chipped:moss_block" },
    { type: "tag", name: "chipped_mossy_cobblestone", tag: "chipped:mossy_cobblestone" },
    { type: "tag", name: "chipped_raw_copper_block", tag: "chipped:raw_copper_block" },
    { type: "tag", name: "chipped_red_mushroom", tag: "chipped:red_mushroom" },
    { type: "tag", name: "chipped_red_nether_bricks", tag: "chipped:red_nether_bricks" },
    { type: "tag", name: "chipped_redstone_lamp", tag: "chipped:redstone_lamp" },
    { type: "tag", name: "chipped_sand", tag: "chipped:sand" },
    { type: "tag", name: "chipped_verdant_froglight", tag: "chipped:verdant_froglight" },
    { type: "tag", name: "chipped_warped_fungus", tag: "chipped:warped_fungus" },
    { type: "tag", name: "chipped_warped_stem", tag: "chipped:warped_stem" },
    { type: "tag", name: "chipped_warped_wart_block", tag: "chipped:warped_wart_block" },
]

