//priority: 10

let $RenderLevelStageEvent = Java.loadClass("net.neoforged.neoforge.client.event.RenderLevelStageEvent")
let $InputEvent$MouseButton$Pre = Java.loadClass("net.neoforged.neoforge.client.event.InputEvent$MouseButton$Pre")
let $ViewportEvent$ComputeCameraAngles = Java.loadClass("net.neoforged.neoforge.client.event.ViewportEvent$ComputeCameraAngles")
let $ViewportEvent$RenderFog = Java.loadClass("net.neoforged.neoforge.client.event.ViewportEvent$RenderFog")
let $RenderFrameEvent$Post = Java.loadClass("net.neoforged.neoforge.client.event.RenderFrameEvent$Post")


let $ClipContext = Java.loadClass("net.minecraft.world.level.ClipContext")
let $ClipContext$Block = Java.loadClass("net.minecraft.world.level.ClipContext$Block")
let $ClipContext$Fluid = Java.loadClass("net.minecraft.world.level.ClipContext$Fluid")
let $MultiBufferSource = Java.loadClass("net.minecraft.client.renderer.MultiBufferSource")
let $PostChain = Java.loadClass("net.minecraft.client.renderer.PostChain")
let $Stage = Java.loadClass("net.neoforged.neoforge.client.event.RenderLevelStageEvent$Stage")
let $OverlayTexture = Java.loadClass("net.minecraft.client.renderer.texture.OverlayTexture")
let $ModelData = Java.loadClass("net.neoforged.neoforge.client.model.data.ModelData")
let $RenderType = Java.loadClass("net.minecraft.client.renderer.RenderType")
let $BufferBuilder = Java.loadClass("com.mojang.blaze3d.vertex.BufferBuilder")
let $VertexFormat = Java.loadClass("com.mojang.blaze3d.vertex.VertexFormat")
let $DefaultVertexFormat = Java.loadClass("com.mojang.blaze3d.vertex.DefaultVertexFormat")
let $HashSet = Java.loadClass("java.util.HashSet")
let $Direction = Java.loadClass("net.minecraft.core.Direction")
let $VertexBuffer = Java.loadClass("com.mojang.blaze3d.vertex.VertexBuffer")
let $Tesselator = Java.loadClass("com.mojang.blaze3d.vertex.Tesselator")
let $PoseStack = Java.loadClass("com.mojang.blaze3d.vertex.PoseStack")
let $GameRenderer = Java.loadClass("net.minecraft.client.renderer.GameRenderer")
let $LevelRenderer = Java.loadClass("net.minecraft.client.renderer.LevelRenderer")
let $RenderSystem = Java.loadClass("com.mojang.blaze3d.systems.RenderSystem")
let $LightTexture = Java.loadClass("net.minecraft.client.renderer.LightTexture")
let $SmoothQuadLighter = Java.loadClass("net.neoforged.neoforge.client.model.lighting.SmoothQuadLighter")
let $BlockColors = Java.loadClass("net.minecraft.client.color.block.BlockColors")
let $Matrix4f = Java.loadClass("org.joml.Matrix4f")
let $ChunkPos = Java.loadClass("net.minecraft.world.level.ChunkPos")
let $FogShape = Java.loadClass("com.mojang.blaze3d.shaders.FogShape")
let $CompoundTag = Java.loadClass("net.minecraft.nbt.CompoundTag")
let $ChatFormatting = Java.loadClass("net.minecraft.ChatFormatting")
let $Component = Java.loadClass("net.minecraft.network.chat.Component")
let $ParticleTypes = Java.loadClass("net.minecraft.core.particles.ParticleTypes")
let $Vec3 = Java.loadClass("net.minecraft.world.phys.Vec3")
let $TagParser = Java.loadClass("net.minecraft.nbt.TagParser")


let $TooltipHandler = Java.loadClass("auviotre.enigmatic.legacy.handlers.TooltipHandler")
let $EnigmaticHandler = Java.loadClass("auviotre.enigmatic.legacy.handlers.EnigmaticHandler")
let $EnigmaticAttachments = Java.loadClass("auviotre.enigmatic.legacy.registries.EnigmaticAttachments")

let $Registries = Java.loadClass("net.minecraft.core.registries.Registries")
let $ConcurrentHashMap = Java.loadClass("java.util.concurrent.ConcurrentHashMap")
let $RandomSource = Java.loadClass("net.minecraft.util.RandomSource")
let $ByteBufferBuilder = Java.loadClass("com.mojang.blaze3d.vertex.ByteBufferBuilder")
let $NbtOps = Java.loadClass("net.minecraft.nbt.NbtOps")
let $LinkedHashMap = Java.loadClass("java.util.LinkedHashMap")

let $ApothicEnchanting = Java.loadClass('dev.shadowsoffire.apothic_enchanting.ApothicEnchanting')

