ServerEvents.tags('item', event => {

    //TODO: immersive_aircraft But is that really necessary? Any aircraft can be stolen
    event.add("waystones:is_teleport_target",[
        'waystones:black_sharestone', 
        'waystones:red_sharestone', 
        'waystones:green_sharestone', 
        'waystones:brown_sharestone', 
        'waystones:blue_sharestone', 
        'waystones:purple_sharestone', 
        'waystones:cyan_sharestone', 
        'waystones:light_gray_sharestone', 
        'waystones:gray_sharestone', 
        'waystones:pink_sharestone', 
        'waystones:lime_sharestone', 
        'waystones:yellow_sharestone', 
        'waystones:light_blue_sharestone', 
        'waystones:magenta_sharestone', 
        'waystones:orange_sharestone', 
        'waystones:black_portstone', 
        'waystones:red_portstone', 
        'waystones:green_portstone', 
        'waystones:brown_portstone', 
        'waystones:blue_portstone', 
        'waystones:purple_portstone', 
        'waystones:cyan_portstone', 
        'waystones:light_gray_portstone', 
        'waystones:gray_portstone', 
        'waystones:pink_portstone', 
        'waystones:lime_portstone', 
        'waystones:yellow_portstone', 
        'waystones:light_blue_portstone', 
        'waystones:magenta_portstone', 
        'waystones:orange_portstone', 
        'waystones:white_portstone',
        'waystones:warp_plate', 
        'waystones:end_stone_waystone', 
        'waystones:blackstone_waystone', 
        'waystones:deepslate_waystone', 
        'waystones:sandy_waystone', 
        'waystones:mossy_waystone', 
        'waystones:waystone',
    ]   )
})
