//tags for block and item at the same time
const sharedTags = [
    { 
        id: 'ars_nouveau:purple_bricks', values: [
        'ars_nouveau:sourcestone_mosaic', 
        'ars_nouveau:sourcestone_basketweave', 
        'ars_nouveau:sourcestone_alternating', 
        'ars_nouveau:sourcestone_large_bricks', 
        'ars_nouveau:sourcestone_small_bricks', 
        'ars_nouveau:gilded_sourcestone_mosaic', 
        'ars_nouveau:gilded_sourcestone_basketweave', 
        'ars_nouveau:gilded_sourcestone_alternating', 
        'ars_nouveau:gilded_sourcestone_large_bricks', 
        'ars_nouveau:gilded_sourcestone_small_bricks', 
        'ars_additions:cracked_sourcestone_large_bricks', 
        'ars_additions:cracked_sourcestone_small_bricks'
        ] 
    },
    { 
        id: 'ars_nouveau:purple_brick_slabs', values: [
            'ars_nouveau:sourcestone_mosaic_slab', 
            'ars_nouveau:sourcestone_basketweave_slab', 
            'ars_nouveau:sourcestone_alternating_slab', 
            'ars_nouveau:sourcestone_large_bricks_slab', 
            'ars_nouveau:sourcestone_small_bricks_slab', 
            'ars_nouveau:gilded_sourcestone_small_bricks_slab', 
            'ars_nouveau:gilded_sourcestone_mosaic_slab', 
            'ars_nouveau:gilded_sourcestone_basketweave_slab', 
            'ars_nouveau:gilded_sourcestone_alternating_slab', 
            'ars_nouveau:gilded_sourcestone_large_bricks_slab'
        ] 
    },
    { 
        id: 'ars_nouveau:sourcestones', values: [
        'ars_nouveau:sourcestone', 
        'ars_nouveau:smooth_sourcestone', 
        ] 
    }
]

ServerEvents.tags('block', event => {

    event.add('ars_nouveau:golem/budding', ["spectrum:budding_topaz", "spectrum:budding_citrine", "spectrum:budding_onyx", "spectrum:budding_moonstone"])
    event.add('ars_nouveau:golem/cluster', ["spectrum:topaz_cluster", "spectrum:citrine_cluster", "spectrum:onyx_cluster", "spectrum:moonstone_cluster"])


    sharedTags.forEach(({ id, values }) => event.add(id, values))
})
ServerEvents.tags('item', event => {
    event.add('ars_nouveau:golem/shard', ["spectrum:topaz_shard", "spectrum:citrine_shard", "spectrum:onyx_shard", "spectrum:moonstone_shard"])


    event.add("ars_nouveau:tier_1_glyphs", [
        'ars_nouveau:glyph_prestidigitation', 
        'ars_nouveau:glyph_pull', 
        'ars_nouveau:glyph_redstone_signal', 
        'ars_nouveau:reset', 
        'ars_nouveau:glyph_rotate', 
        'ars_nouveau:glyph_rune', 
        'ars_nouveau:glyph_snare', 
        'ars_elemental:glyph_spark', 
        'ars_nouveau:glyph_light', 
        'ars_elemental:glyph_conjure_terrain', 
        'ars_nouveau:glyph_craft', 
        'ars_nouveau:glyph_cut', 
        'ars_nouveau:glyph_delay', 
        'ars_nouveau:glyph_dispel', 
        'ars_nouveau:glyph_evaporate', 
        'ars_nouveau:glyph_fell', 
        'ars_nouveau:glyph_freeze', 
        'ars_nouveau:glyph_harm', 
        'ars_nouveau:glyph_harvest', 
        'ars_nouveau:glyph_ignite', 
        'ars_nouveau:glyph_interact', 
        'ars_nouveau:glyph_pickup', 
        'ars_nouveau:glyph_gust', 
        'ars_nouveau:glyph_launch', 
        'ars_nouveau:glyph_leap', 
        'ars_nouveau:glyph_place_block', 
        'ars_nouveau:glyph_bubble', 
        'ars_nouveau:glyph_bounce', 
        'ars_nouveau:glyph_phantom_block', 
        'ars_nouveau:glyph_projectile', 
        'ars_nouveau:glyph_pantomime', 
        'ars_nouveau:glyph_break', 
        'ars_nouveau:glyph_underfoot', 
        'ars_nouveau:glyph_touch', 
        'ars_nouveau:glyph_summon_steed',
        'ars_nouveau:glyph_summon_wolves', 
        'ars_nouveau:glyph_toss', 
        'ars_nouveau:glyph_wind_burst', 
        'ars_nouveau:wololo', 
        'ars_nouveau:glyph_amplify', 
        'ars_nouveau:glyph_randomize', 
        'ars_nouveau:glyph_sensitive',
        'reliquified_ars_nouveau:glyph_multicast', 
        'ars_controle:glyph_filter_or', 
        'ars_controle:glyph_filter_not', 
        'ars_controle:glyph_filter_above', 
        'ars_controle:glyph_filter_below', 
        'ars_controle:glyph_filter_level', 
        'ars_controle:glyph_filter_random', 
        'ars_controle:glyph_filter_xnor', 
        'ars_controle:glyph_filter_xor', 
        'ars_elemental:glyph_aerial_filter',
        'ars_elemental:glyph_aquatic_filter', 
        'ars_elemental:glyph_fiery_filter', 
        'ars_elemental:glyph_insect_filter', 
        'ars_elemental:glyph_not_aerial_filter', 
        'ars_elemental:glyph_not_aquatic_filter', 
        'ars_elemental:glyph_not_fiery_filter', 
        'ars_elemental:glyph_not_insect_filter', 
        'ars_elemental:glyph_not_summon_filter', 
        'ars_elemental:glyph_not_undead_filter', 
        'ars_elemental:glyph_summon_filter', 
        'ars_elemental:glyph_undead_filter',
        'toomanyglyphs:glyph_ray', 
        'not_enough_glyphs:glyph_plow', 
        'toomanyglyphs:glyph_reverse_direction', 
        'not_enough_glyphs:glyph_ride', 
        'toomanyglyphs:glyph_filter_animal', 
        'toomanyglyphs:glyph_filter_block', 
        'not_enough_glyphs:glyph_filter_dark', 
        'toomanyglyphs:glyph_filter_entity', 
        'toomanyglyphs:glyph_filter_item', 
        'not_enough_glyphs:glyph_filter_light', 
        'toomanyglyphs:glyph_filter_living', 
        'toomanyglyphs:glyph_filter_monster', 
        'toomanyglyphs:glyph_filter_living_not_monster', 
        'toomanyglyphs:glyph_filter_living_not_player', 
        'toomanyglyphs:glyph_filter_player',
        'ars_trinkets:glyph_filter_not_self',
        'ars_trinkets:glyph_filter_self',
        'ars_nouveau:glyph_self',
        'arsomega:glyph_overhead',
    ])
    event.add("ars_nouveau:tier_2_glyphs", [
        'ars_elemental:glyph_arc_projectile', 
        'ars_nouveau:glyph_ender_inventory', 
        'ars_nouveau:glyph_animate_block', 
        'ars_elemental:glyph_bubble_shield', 
        'ars_elemental:glyph_charm', 
        'ars_nouveau:glyph_cold_snap', 
        'ars_nouveau:glyph_conjure_water', 
        'ars_nouveau:glyph_crush', 
        'ars_elemental:glyph_discharge', 
        'ars_elemental:glyph_envenom', 
        'ars_nouveau:glyph_exchange', 
        'ars_nouveau:glyph_explosion', 
        'ars_nouveau:glyph_firework', 
        'ars_nouveau:glyph_flare', 
        'ars_nouveau:glyph_gravity', 
        'ars_nouveau:glyph_grow', 
        'ars_nouveau:glyph_heal', 
        'ars_nouveau:glyph_infuse', 
        'ars_nouveau:glyph_invisibility', 
        'ars_nouveau:glyph_name', 
        'ars_elemental:glyph_phantom_grasp', 
        'ars_elemental:glyph_poison_spores', 
        'ars_controle:glyph_precise_delay', 
        'ars_nouveau:glyph_slowfall', 
        'ars_nouveau:glyph_smelt', 
        'ars_elemental:glyph_spike', 
        'ars_elemental:glyph_watery_grave', 
        'ars_nouveau:glyph_wind_shear', 
        'ars_elemental:glyph_propagator_arc', 
        'starbunclemania:glyph_pickup_fluid', 
        'starbunclemania:glyph_place_fluid', 
        'ars_nouveau:glyph_sense_magic', 
        'ars_hex:glyph_soul_shatter',
        'ars_nouveau:glyph_aoe', 
        'ars_nouveau:glyph_pierce', 
        'ars_nouveau:glyph_accelerate', 
        'ars_nouveau:glyph_duration_down', 
        'ars_nouveau:glyph_dampen', 
        'ars_nouveau:glyph_decelerate', 
        'ars_nouveau:glyph_extend_time', 
        'ars_nouveau:glyph_extract', 
        'ars_nouveau:glyph_fortune',
        'ars_elemental:glyph_mist', 
        'ars_elemental:glyph_geyser', 
        'ars_elemental:glyph_slip_feet', 
        'ars_elemental:glyph_summon_bee', 
        'ars_elemental:glyph_summon_slime',
        'toomanyglyphs:glyph_chaining', 
        'not_enough_glyphs:glyph_feed', 
        'not_enough_glyphs:glyph_propagate_plane', 
        'not_enough_glyphs:glyph_contingency_blink', 
        'not_enough_glyphs:glyph_contingency_death', 
        'not_enough_glyphs:glyph_contingency_time', 
        'not_enough_glyphs:glyph_contingency_fall', 
        'not_enough_glyphs:glyph_contingency_fire', 
        'not_enough_glyphs:glyph_contingency_heal', 
        'not_enough_glyphs:glyph_contingency_health', 
        'toomanyglyphs:glyph_filter_is_baby', 
        'toomanyglyphs:glyph_filter_is_mature',
        'arsomega:glyph_missile', 
        'arsomega:glyph_propagate_underfoot', 
        'arsomega:glyph_flatten', 
        'ars_scalaes:glyph_resize', 
        'arsomega:glyph_propagate_missile', 
        'arsomega:glyph_propagate_projectile', 
        'arsomega:glyph_propagate_overhead', 
        'arsomega:glyph_propagate_self',
    ])
    event.add("ars_nouveau:tier_3_glyphs", [
        'ars_elemental:glyph_homing_projectile', 
        'ars_additions:glyph_recall', 
        'ars_additions:glyph_retaliate', 
        'ars_nouveau:glyph_blink', 
        'ars_nouveau:glyph_burst', 
        'ars_elemental:glyph_conflagrate', 
        'ars_nouveau:glyph_fangs', 
        'ars_nouveau:glyph_glide', 
        'ars_nouveau:glyph_hex', 
        'ars_nouveau:glyph_intangible', 
        'ars_elemental:glyph_life_link', 
        'ars_nouveau:glyph_lightning', 
        'ars_nouveau:glyph_linger', 
        'ars_additions:glyph_mark', 
        'ars_elemental:glyph_nullify_defense', 
        'ars_nouveau:glyph_orbit', 
        'ars_nouveau:rewind', 
        'ars_nouveau:glyph_summon_decoy', 
        'ars_nouveau:glyph_summon_undead', 
        'ars_nouveau:glyph_summon_vex', 
        'ars_nouveau:glyph_wall', 
        'ars_nouveau:glyph_wither', 
        'ars_elemental:glyph_propagator_homing', 
        'ars_nouveau:glyph_split',
        'ars_elemental:glyph_cauterize',
        'ars_elemental:glyph_cavitate',
        'ars_elemental:glyph_oxidize',
        'ars_elemental:glyph_rage',
        'ars_elemental:glyph_water_jet',
        'not_enough_glyphs:glyph_trail',
    ])
    event.add("ars_nouveau:threads", [
        'ars_nouveau:thread_depths', 
        'ars_hex:thread_magic_proficiency', 
        'ars_elemental:thread_spore', 
        'ars_elemental:thread_shock', 
        'ars_nouveau:thread_drygmy', 
        'ars_nouveau:thread_high_step', 
        'ars_nouveau:thread_spellpower', 
        'not_enough_glyphs:thread_fire_focus', 
        'ars_nouveau:thread_life_drain', 
        'ars_nouveau:thread_starbuncle', 
        'not_enough_glyphs:thread_knockback', 
        'ars_nouveau:thread_feather', 
        'not_enough_glyphs:thread_earth_focus', 
        'not_enough_glyphs:thread_slow_power', 
        'not_enough_glyphs:thread_scritchance', 
        'ars_nouveau:thread_gliding', 
        'not_enough_glyphs:thread_scritdamage', 
        'ars_nouveau:thread_immolation', 
        'ars_nouveau:thread_amethyst_golem', 
        'ars_nouveau:thread_magic_capacity', 
        'not_enough_glyphs:thread_air_focus', 
        'not_enough_glyphs:thread_sharp_paper', 
        'ars_nouveau:thread_kindling', 
        'ars_elemental:thread_summon', 
        'ars_nouveau:thread_wixie', 
        'ars_nouveau:thread_heights', 
        'ars_nouveau:thread_whirlisprig', 
        'not_enough_glyphs:thread_shaper_focus', 
        'not_enough_glyphs:thread_wild_magic', 
        'ars_nouveau:thread_chilling', 
        'ars_nouveau:thread_undying', 
        'not_enough_glyphs:thread_water_focus', 
        'ars_nouveau:thread_warding', 
        'not_enough_glyphs:thread_summon_focus', 
        'not_enough_glyphs:thread_cheap_damage', 
        'ars_additions:thread_reach',
        'ars_hex:thread_soul_ward', 
        'ars_hex:thread_soul_spoils', 
        'ars_nouveau:thread_repairing'
    ])

    event.add('ars_nouveau:horn_food', [
        'arsdelight:mendosteen_hornbeer', 
        'arsdelight:bastion_hornbeer', 
        'arsdelight:bombegrante_hornbeer', 
        'arsdelight:frostaya_hornbeer', 
        'arsdelight:source_berry_hornbeer'
    ])

    event.add('ars_nouveau:archwood_saplings', ['ars_nouveau:blue_archwood_sapling', 'ars_nouveau:purple_archwood_sapling', 'ars_nouveau:red_archwood_sapling', 'ars_nouveau:green_archwood_sapling', 'ars_elemental:yellow_archwood_sapling'])
    sharedTags.forEach(({ id, values }) => event.add(id, values))
})

ServerEvents.tags("entity_type", event => {
    event.add("ars_nouveau:drygmy_blacklist", "#c:bosses")
    event.add("ars_nouveau:jar_blacklist", "#c:bosses")
})



