ServerEvents.tags('item', event => {

    event.add('nutritional:nutrient/source', ['#ars_nouveau:magic_food'])

    event.add('nutritional:nutrient/fruit', [
        // Arsdelight
        '#arsdelight:jelly',

        'arsdelight:mendosteen_pie_slice',
        'arsdelight:bastion_pie_slice',
        'arsdelight:bombegrante_pie_slice',
        'arsdelight:frostaya_pie_slice',
        'arsdelight:flashpine_pie_slice',
        'arsdelight:dawnberry_pie_slice',
        'arsdelight:lightchee_pie_slice',
        'arsdelight:source_berry_pie_slice',

        'arsdelight:source_berry_cookie',

        'arsdelight:mendosteen_tea',
        'arsdelight:bastion_tea',
        'arsdelight:bombegrante_tea',
        'arsdelight:frostaya_tea',
        'arsdelight:source_berry_tea',

        'arsdelight:mendosteen_hornbeer',
        'arsdelight:bastion_hornbeer',
        'arsdelight:bombegrante_hornbeer',
        'arsdelight:frostaya_hornbeer',
        'arsdelight:source_berry_hornbeer',

        'arsdelight:activated_mendosteen_jam',
        'arsdelight:activated_bastion_jam',
        'arsdelight:neutralized_bombegrante_jam',
        'arsdelight:neutralized_frostaya_jam',
        'arsdelight:source_berry_jam',

        // Spectrum
        '#spectrum:star_candies',
        'spectrum:amethyst_rock_candy',
        'spectrum:aqua_regia',
        'spectrum:azalea_tea',
        'spectrum:bloodboil_syrup',
        'spectrum:bodacious_berry_bar',
        'spectrum:cheong',
        'spectrum:chrysocolla',
        'spectrum:citrine_rock_candy',
        'spectrum:demon_tea',
        'spectrum:fissure_plum',
        'spectrum:glass_peach',
        'spectrum:glistering_jelly_tea',
        'spectrum:golden_bristle_tea',
        'spectrum:jade_jelly',
        'spectrum:jade_wine',
        'spectrum:mermaids_jam',
        'spectrum:moonstone_rock_candy',
        'spectrum:moonstruck_nectar',
        'spectrum:myceylon_apple_pie',
        'spectrum:nectardew_burgeon',
        'spectrum:onyx_rock_candy',
        'spectrum:peach_jam',
        'spectrum:peaches_flambe',
        'spectrum:pure_alcohol',
        'spectrum:reprise',
        'spectrum:restoration_tea',
        'spectrum:rock_candy',
        'spectrum:sawblade_holly_berry',
        'spectrum:slushslide',
        'spectrum:topaz_rock_candy',
        'spectrum:shaved_ice',
        'spectrum:jelly_slug',
        'spectrum:faded_koi',
        'spectrum:crawfish_cocktail',
        'spectrum:peach_cream',
        'spectrum:junket',
        'spectrum:banyash',
        'spectrum:dragonbone_broth',
        'spectrum:chauve_souris_au_vin',
        'spectrum:triple_meat_pot_stew',
        'spectrum:ashen_tart',
        'spectrum:scone',
        'spectrum:fresh_chocolate',

        // Eidolon Edoni
        'eidolon_edoni:shaved_ice',
        'eidolon_edoni:jelly_slug',
        'eidolon_edoni:cherry_candy',

        // Eidolon Repraised
        'eidolon_repraised:red_candy',
    ])

    event.add('nutritional:nutrient/protein', [
        // Arsdelight
        '#arsdelight:raw_wilden_meat',
        '#arsdelight:cooked_wilden_meat',
        '#arsdelight:raw_chimera',
        '#arsdelight:cooked_chimera',

        'arsdelight:wilden_skewer',
        'arsdelight:grilled_wilden_skewer',
        'arsdelight:chimera_skewer',
        'arsdelight:grilled_chimera_skewer',

        'arsdelight:wilden_sauce',

        'arsdelight:arch_soup',
        'arsdelight:wilden_stew',
        'arsdelight:bowl_of_wilden_salad',
        'arsdelight:bowl_of_honey_glazed_chimera',

        'arsdelight:mendosteen_chicken',
        'arsdelight:bastion_pork',
        'arsdelight:bombegrante_steak',
        'arsdelight:frostaya_mutton',

        // Spectrum
        'spectrum:bagnun',
        'spectrum:banyash',
        'spectrum:chauve_souris_au_vin',
        'spectrum:cooked_lizard_meat',
        'spectrum:crawfish',
        'spectrum:crawfish_cocktail',
        'spectrum:dragonbone_broth',
        'spectrum:faded_koi',
        'spectrum:fishcake',
        'spectrum:hare_roast',
        'spectrum:koi',
        'spectrum:le_fishe_au_chocolat',
        'spectrum:lizard_meat',
        'spectrum:meatloaf',
        'spectrum:meatloaf_sandwich',
        'spectrum:rabbit_cream_pie',
        'spectrum:surstromming',
        'spectrum:triple_meat_pot_pie',
        'spectrum:triple_meat_pot_stew',
        'spectrum:demon_trifle',
        'spectrum:monster_trifle',

        // Eidolon Edoni
        'eidolon_edoni:heart_terrine_slice',
        'eidolon_edoni:avennian_scrambled_egg',
        'eidolon_edoni:avennian_stew',
        'eidolon_edoni:fried_heart',
        'eidolon_edoni:jockey_pie_slice',
        'eidolon_edoni:oanna_chicken_congee',
        'eidolon_edoni:sildrian_beef',
        'eidolon_edoni:stuffed_wither_skeleton_skull_bowl',
        'eidolon_edoni:blood_bagel_with_curry',
        'eidolon_edoni:blood_hot_dog_with_petal_salad',
        'eidolon_edoni:heart_wrap',
        'eidolon_edoni:choking_sandwich',
        'eidolon_edoni:curry_fish_ball',
        'eidolon_edoni:curry_porkchop',
        'eidolon_edoni:seafood_curry',
        'eidolon_edoni:cream_of_mushroom_soup',
        'eidolon_edoni:cold_noodle',
        // Starcatecher and tide fishes (also some vanilla one but meh)
        '#c:foods/raw_fish'
    ])

    event.add('nutritional:nutrient/grain', [
        // Arsdelight
        'arsdelight:mendosteen_pie_slice',
        'arsdelight:bastion_pie_slice',
        'arsdelight:bombegrante_pie_slice',
        'arsdelight:frostaya_pie_slice',
        'arsdelight:flashpine_pie_slice',
        'arsdelight:dawnberry_pie_slice',
        'arsdelight:lightchee_pie_slice',
        'arsdelight:source_berry_pie_slice',

        'arsdelight:source_berry_cookie',
        'arsdelight:source_berry_cupcake',
        'arsdelight:horn_roll',

        // Spectrum
        'spectrum:ashen_tart',
        'spectrum:berliner',
        'spectrum:cream_pastry',
        'spectrum:fresh_chocolate',
        'spectrum:honey_pastry',
        'spectrum:jaramel',
        'spectrum:jaramel_tart',
        'spectrum:lucky_roll',
        'spectrum:mermaids_popcorn',
        'spectrum:myceylon_cookie',
        'spectrum:myceylon_pumpkin_pie',
        'spectrum:puff_tart',
        'spectrum:salted_jaramel_tart',
        'spectrum:scone',
        'spectrum:weeping_tart',
        'spectrum:whispy_tart',
        'spectrum:meatloaf_sandwich',

        // Eidolon Edoni
        'eidolon_edoni:bread_with_curry',
        'eidolon_edoni:cold_noodle',
        'eidolon_edoni:cream_pasta_with_petals',
        'eidolon_edoni:oanna_mooncake_slice',
        'eidolon_edoni:rice_with_curry',
        'eidolon_edoni:calx_croquette',
        'eidolon_edoni:fried_avenna_dumpling',
        'eidolon_edoni:jockey_pie_slice',
        'eidolon_edoni:mixed_porridge',
        'eidolon_edoni:oanna_chicken_congee',
        'eidolon_edoni:rustic_loaf_slice_with_curry',
        'eidolon_edoni:tortilla_with_curry',
        'eidolon_edoni:slices_of_bread_with_curry',
        'eidolon_edoni:toasts_with_curry',
        'eidolon_edoni:fried_dough_with_curry',
        'eidolon_edoni:rice_bread_with_curry',
        'eidolon_edoni:hardtack_with_curry',
        'eidolon_edoni:blood_bagel_with_curry',
        'eidolon_edoni:heart_wrap',
        'eidolon_edoni:popcorn_bat',
        'eidolon_edoni:choking_sandwich',
        'eidolon_edoni:tteokbokki',
    ])

    event.add('nutritional:nutrient/vegetable', [
        // Arsdelight
        'arsdelight:arch_sauce',
        'arsdelight:arch_soup',
        'arsdelight:wilden_stew',
        'arsdelight:bowl_of_wilden_salad',

        // Spectrum
        'spectrum:aloe_leaf',
        'spectrum:enchanted_golden_carrot',
        'spectrum:kimchi',
        'spectrum:mellow_shallot_soup',
        'spectrum:nightdew_sprout',
        'spectrum:prickly_bayleaf',
        'spectrum:sedatives',
        'spectrum:suspicious_brew',
        'spectrum:surstromming',
        'spectrum:myceylon_cookie',
        'spectrum:jaramel_trifle',
        'spectrum:honey_pastry',
        'spectrum:rabbit_cream_pie',
        'spectrum:peaches_flambe',
        'spectrum:hare_roast',
        'spectrum:cream_pastry',
        'spectrum:berliner',
        'spectrum:bagnun',
        'spectrum:myceylon_pumpkin_pie',
        'spectrum:puff_tart',
        'spectrum:whispy_tart',
        'spectrum:weeping_tart',
        'spectrum:triple_meat_pot_pie',
        'spectrum:peach_jam',
        'spectrum:peach_cream',
        'spectrum:junket',
        'spectrum:banyash',
        'spectrum:dragonbone_broth',
        'spectrum:meatloaf_sandwich',
        'spectrum:chauve_souris_au_vin',
        'spectrum:triple_meat_pot_stew',
        'spectrum:ashen_tart',
        'spectrum:scone',
        'spectrum:demon_trifle',
        'spectrum:monster_trifle',

        // Eidolon Edoni
        'eidolon_edoni:cream_of_mushroom_soup',
        'eidolon_edoni:rice_with_curry',
        'eidolon_edoni:avennian_stew',
        'eidolon_edoni:grilled_avennian_sprig',
        'eidolon_edoni:rustic_loaf_slice_with_curry',
        'eidolon_edoni:tortilla_with_curry',
        'eidolon_edoni:slices_of_bread_with_curry',
        'eidolon_edoni:toasts_with_curry',
        'eidolon_edoni:fried_dough_with_curry',
        'eidolon_edoni:rice_bread_with_curry',
        'eidolon_edoni:hardtack_with_curry',
        'eidolon_edoni:petal_salad',
        'eidolon_edoni:grilled_vegetable_platter_plate',
        'eidolon_edoni:blood_hot_dog_with_petal_salad',
        'eidolon_edoni:tteokbokki',
        'eidolon_edoni:curry_fish_ball',
        'eidolon_edoni:curry_porkchop',
        'eidolon_edoni:seafood_curry',
        'eidolon_edoni:bechamel_sauce',
        'eidolon_edoni:sildrian_beef',
        'eidolon_edoni:avennian_scrambled_egg',
        'eidolon_edoni:fried_avenna_dumpling',
        'eidolon_edoni:calx_croquette',
        'eidolon_edoni:mirechoco',
        'eidolon_edoni:cold_noodle',

        // Eidolon Repraised
        'eidolon_repraised:red_candy',
        'eidolon_repraised:grape_candy',
    ])

    event.add('nutritional:nutrient/dairy', [
        // Arsdelight
        'arsdelight:source_berry_cupcake',

        // Spectrum
        'spectrum:clotted_cream',
        'spectrum:demon_trifle',
        'spectrum:hot_chocolate',
        'spectrum:jaramel_trifle',
        'spectrum:junket',
        'spectrum:karak_chai',
        'spectrum:monster_trifle',
        'spectrum:peach_cream',
        'spectrum:salted_jaramel_trifle',
        'spectrum:slushslide',
        'spectrum:lucky_roll',
        'spectrum:le_fishe_au_chocolat',
        'spectrum:bodacious_berry_bar',
        'spectrum:rabbit_cream_pie',
        'spectrum:peaches_flambe',
        'spectrum:hare_roast',
        'spectrum:cream_pastry',
        'spectrum:berliner',
        'spectrum:bagnun',
        'spectrum:myceylon_pumpkin_pie',
        'spectrum:puff_tart',
        'spectrum:whispy_tart',
        'spectrum:weeping_tart',
        'spectrum:triple_meat_pot_pie',
        'spectrum:meatloaf_sandwich',
        'spectrum:chauve_souris_au_vin',
        'spectrum:triple_meat_pot_stew',
        'spectrum:ashen_tart',
        'spectrum:scone',
        'spectrum:myceylon_apple_pie',
        'spectrum:fresh_chocolate',

        // Eidolon Edoni
        'eidolon_edoni:bechamel_sauce',
        'eidolon_edoni:cream_of_mushroom_soup',
        'eidolon_edoni:cream_pasta_with_petals',
        'eidolon_edoni:mirechoco',
        'eidolon_edoni:curry_porkchop',
        'eidolon_edoni:oanna_mooncake_slice',
    ])

})
